# Setup
title: Matthew Clark
description: Thoughts and writings about technology by Matthew Clark.
tagline: Thoughts and writings about technology by Matthew Clark.
url: https://matthewclark.ca
baseurl: "/"
url: "/"
permalink: pretty

# Dependencies
highlighter:      pygments

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

paginate: 5

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - backup/

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Matthew Clark
  url: https://matthewclark.ca
  email: matthew@matthewclark.ca
  picture: /assets/images/Matthew-Clark-min.jpg
  linkedin: https://www.linkedin.com/in/matthewthoclark
  twitter: https://twitter.com/MatthewThoClark
  github: https://github.com/Zwitty/

# Custom vars
version: 2.0.0
